name: docs
on:
  push:
    branches:
      - main
jobs:
  static:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v3
        with:
          # need entire history
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: generate site
        run: |
          go mod tidy
          make ssg
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: publish to pgs
        uses: picosh/pgs-action@v3
        with:
          user: erock
          key: ${{ secrets.PRIVATE_KEY }}
          src: './public/'
          project: "starfx-docs-${{ steps.vars.outputs.sha_short }}"
          promote: "starfx-prod"
          retain: "starfx-docs"
