name: release to npm

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: get version
        id: vars
        run: echo ::set-output name=version::$(echo ${{github.ref_name}} | sed 's/^v//')
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.com
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: publish
        run: npm publish --access=public
        working-directory: .
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
